### ISSUE TITLE
NAYIF-1 AssertionError

### ISSUE THREAD

**Issue by janvgils** [kng/satnogs_gr-satellites#1]
I have running this great development for almost 2 days and things look ok.
There was only the following error during one of the NAYIF-1 passes.

It seems to be triggered by the `kiss_satnogs.py` script.

```
Dec 01 22:10:43 exomars satnogs-client[14637]: gr-satellites: Observation: 3225264, Norad: 42017, Name: NAYIF-1_EO-88, Script: satnogs_bpsk.py
Dec 01 22:10:43 exomars satnogs-client[14637]: gr-satellites: Starting observation 3225264
Dec 01 22:10:43 exomars satnogs-client[14637]: gr-satellites: Decoding NAYIF-1
Dec 01 22:10:45 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:10:45 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:10:45 exomars satnogs-client[14637]: [INFO] Opening Generic RTL2832U OEM :: 00000001...
Dec 01 22:10:46 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:10:46 exomars satnogs-client[14637]: [R82XX] PLL not locked!
Dec 01 22:10:46 exomars satnogs-client[14637]: [INFO] Using format CF32.
Dec 01 22:10:47 exomars satnogs-client[14637]: Allocating 15 zero-copy buffers
Dec 01 22:19:45 exomars satnogs-client[14637]: 4
Dec 01 22:19:46 exomars satnogs-client[14637]: gr-satellites: Observation: 3225264, Norad: 42017, Name: NAYIF-1_EO-88, Script: satnogs_bpsk.py
Dec 01 22:19:46 exomars satnogs-client[14637]: gr-satellites: Stopping observation 3225264
Dec 01 22:19:46 exomars satnogs-client[14637]: gr-satellites: Got some telemetry!
Dec 01 22:19:46 exomars satnogs-client[14637]: gr-satellites: Got some kiss data!
Dec 01 22:19:46 exomars satnogs-client[14637]: Traceback (most recent call last):
Dec 01 22:19:46 exomars satnogs-client[14637]:   File "/usr/local/bin/kiss_satnogs.py", line 88, in <module>
Dec 01 22:19:46 exomars satnogs-client[14637]:     frame_tuples = list(read_kiss_frames(kiss_file))
Dec 01 22:19:46 exomars satnogs-client[14637]:   File "/usr/local/bin/kiss_satnogs.py", line 58, in read_kiss_frames
Dec 01 22:19:46 exomars satnogs-client[14637]:     assert((parts_len - 1) % 4 == 0)
Dec 01 22:19:46 exomars satnogs-client[14637]: AssertionError
Dec 01 22:19:46 exomars satnogs-client[14637]: gr-satellites: Got something in the log!
Dec 01 22:20:30 exomars satnogs-client[14637]: gr-satellites: Observation: 3230832, Norad: 43137, Name: FOX-1D_AO-92, Script: satnogs_amsat_fox_duv_decoder.py
Dec 01 22:20:30 exomars satnogs-client[14637]: gr-satellites: Satellite not supported
Dec 01 22:20:32 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:20:32 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:20:32 exomars satnogs-client[14637]: [INFO] Opening Generic RTL2832U OEM :: 00000001...
Dec 01 22:20:33 exomars satnogs-client[14637]: Found Rafael Micro R820T tuner
Dec 01 22:20:33 exomars satnogs-client[14637]: [R82XX] PLL not locked!
Dec 01 22:20:33 exomars satnogs-client[14637]: [INFO] Using format CF32.
Dec 01 22:20:33 exomars satnogs-client[14637]: Allocating 15 zero-copy buffers
```
Who has seen behavior before and is this that can be fixed?

I almost forgot, below the log file that belongs to the observation.

```
cat /tmp/.satnogs/grsat_3225264.log
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 1 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode fail (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 1)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0 bytes (interleaver path 0)
gr::log :DEBUG: decode_rs0 - Reed-Solomon decode corrected 0
```

**Comment by kng** [comment]
It would probably be good to have a look at the kiss file /tmp/.satnogs/grsat_3225264.kss with some software that can analyze kiss files.
At a first glance I would guess that file is broken somehow. Not optimal that the kiss to binary doesn't handle that properly.
I have also changed the grsat-wrapper.sh to send SIGTERM instead of SIGKILL and only on the gr-satellites pid lauched in the pre-script.

**Comment by janvgils** [comment]
Maybe it is the `gr::log :DEBUG: decode_rs0 - Reed-Solomon decode fail (interleaver path 0)` lets see what happens the next couple of observations.

In  the meantime I have replaced the `grsat-wrapper.sh` with the one of you latest commit.

**Comment by kng** [comment]
Please submit a dump of the kiss file, like: base64 /tmp/.satnogs/grsat_3225264.kss

**Comment by janvgils** [comment]
`base64 grsat_3225264.kss`

```
wAkAAAF2ICaJR8DAANAIBVAUkFUfsAAAAAAHMWLBwcGB29wAzFtVAQAwEAQBAEgARERfyG/7pAXT
Yl5bukq6vw9VOAAPdFVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBAD
AQBAEARVVVRVVVVVVVUBAEAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBAEAQBAEARVVV
RVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUB
ADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUAAAAAAAAAAAAAwMAJAAABdiAmnLLAwADR
CAVQFJBVH7AAAAAABzFiwcHBgdvcAMxbVQEAMBAEAQBIAEREX8h/+6QFU2IsG7kKur8PVTgAD3Rh
ci1TQSDh3s8gyOHb3cogx+Hd1sfBISDH5Mcg5Mft3S0xIMPm4SDe49EgxdXY5Mfa7SDMx+Pa7SDj
5CDP5uHJIMfhxePH0cfKIObh3s8g2uPhINrh7CDI5MfG7SDd0e3eIOPkINjhyMkgx+Hl5M/TySDH
4cXjx9HHyu3m5CDj5CDH4czH49rJIMfhw+PR7d/tySDd7SDH4dTH0d7JAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwAkAAAF2ICbDJcDAANMIBVAUkFUfsAAAAAAH
MWLBgYGB29wAzFtVAQAwEAQBAEgARERfyH/7pAVzYembtwq6vw9VOAAPdGFyLVNBIN/jxyDex+Mg
3dHt3iDFz8fRySDH4ePU0ebaIOPkIOPR39Ig483jzyDI5CDRx9TPIOHh3dbHwSDm5eMgxcjRx+Xt
4yDH4d7H0+PtoSDN1ckgx+Hj2NHm1O0g5t3H2OPJIOHmysflIMjH4cXU0cfdINrh7CDj5ePK7QAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAwMAJAAABdiAm1ojAwADUCAVQFJBVH7AAAAAABzFiwYGBgdvcAMxbVQEA
MBAEAQBH/EREX7hP+7QFU2HY+7bKur8PVTgAD3Rhci1TQSDH5Mcgy+PRySDH08rL48fRINXHzcgg
x+HT4+Ygx+HU7c4g483jzyDI5CDRx9TPIMLhIOPfyubjIN3tIOPM4+baySDV293t0ckg4+Qgw8jk
x8Eg5sjkx8ogx+HF48fRx8og3sjhIMPfy9Eg4+Qg2tTRySDT5ObHyi4g5sfhwuQgw9XIzcogzMfj
2sfKIM/m4ckgx+HF48fRx8og3sfP0ckg2uHsIMjkx8Egw97jx9EgxdXY5Mfa7ckAAAAAAAAAAAAA
AADAwAkAAAF2ICbqJsDAANUIBVAUkFKfsAAAAAAHMWLBgYFB29wAzFtVAQAwEAQBAEgARERfyE/7
pAVDYdk7ttq6vw9VOAAPdGFyLVNBIObh3s8g5N7UINrh7CDU2sfRIOPl48rtIN7V7c/JIOHh1Mfa
0ckgx+HF48fRx8rtySDa5tTJIMjkyiDO4e3dySDH4dPm7c/tIObH4crtIMPY4d4g2uHt5ccg1cfN
yCDH4dPj5iDH4dTtziDjzePPIMjkINHH1M8gwuEg49/K5uMg4d7IICLdysfJIMfh2tHIIgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMAJAAABdiAm/m3A
wADWCAVQFTBVH6cAAAAABzFiwYGBQdvcAMxbVQEAMBAEAQBIAEREX8h/+6QF82Jf+8taur8PVTgA
D3Rhci1TQSDH4d7V7c/JIOXtICLI0d7sINHm0yDH4dTRx+3dIOPHIMjk0uEg3cfh5tjH5aEgze3L
IMfh2Obt4SDH4eTH7d0g4e0g3cfh5NnRySDN4cfloSDkx+3dIObez9HlIOTH7d0g5t/hIMfh2tHI
IMrR1sflIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDACQAAAXYgJxHfwMAA1wgFUBSQVR+nAAAA
AAc6osGBgUHb3ADMW1UBAEAQBAEASABERF/If/ukBaNiK8vIyrq/D1U4AA90/wAA////AACBNRC+
AP+FAQAMA+gABADIAQcABgAAAAEAAAOPAP/OAAAAMgBkAMgdsB2wHbAdsB2wAPoABp8RogAAAAAA
AAAAAAAuAC8AKwAvADP/Qf8BAAAZAAEAAAOhZQpGQ2UzQ2UKRkNlM0NlCkZDZTNDZQpGQ2UzQ2UK
RkNlM0NlRjExdDkwMXRERnQ2RXQyMTFjQkFxOEFxNjljCgpGQ2UzQ2UKRkNlM0NlCkZDZTNDZQpG
Q2UzQ2UKRkNlM0NlRjExdDnAwAkAAAF2ICclM8DAANvcCAVQFJBSn6cAAAAABzFiwYGBQdvcAMxb
VQEAMBAEAQBH/EREX8if+6QFU2HY68Zqur8PVTkAD3Q5vufuXRM+y7PtCzsBADAQBAEAQIAd+nDS
Oc7o7s0TRMw0LRdBAQBAEAQBAEBwHfpxAjn+7e9NF0rNNF0jRQEAMBAEAQBAcB36cL05/u/vzSNO
zbSNO0gBAEAQBAEAQGAd+dDFOj7w8C0vUs50zVNIAQAwEAQBAEBgHflAxTpO8fCdO1XO9P1jSwEA
QBAEAQBAUB35QNI6PvfxDU9Xz3Utb00BAEAQBAEAQFAd+LDFOk708W1fWNA1XXtQAQBAEAQBAEBA
HfgQvcDACQAAAXYgJziHwMAAwQgFUBSQUp+nAAAAAAc0osGBgUHb3ADMW1UBADAQBAEASABERF/I
f/ukBfNiXuvKisq/D1U5AA90Om758c1rW9D1jYdUAQAwEAQBAEAwHfgQxTqu+vI9d1/R9b2LWAEA
MBAEAQBAMB33gL06nvzynYdh0rXtl1sBADAQBAEAQCAd9uDFOv7+8v2PZdO2HadeAQAwEAQBAEAg
HfbgxTq+//N9l1/Sdk2vWgELcawEAQagFmX9YOo6/wDzzaM5z3Ztu04BDbFIBAEAQBTx/NEPOv8D
872nHcs2bWdSAQjxlAQmAFAGZf8A9jr/BfPtpxjK9jynVwEAsBAEOYBQBCn80QLAwAkAAAF2ICfo
BcDAAMoIBVAUkFUfpwAAAAAHL2LBgYFB29wAzFtVAQAwEAQBAEf8RERfyF/7tAVzYglr1xrKzw9V
OQAPdDgezejMKwHDrqwe/wEAQBAEAQBA4B3/kL04PtDpHEsHxO9MRwMBADAQBAEAQNAd/5DFOG7R
6YxnDMYvvGMHAQBAEAQBAEDQHf8AvThu1Onsgw/HMCxzDgEAQBAEAQBA0B3/AL04btXqXJsSx/C8
dxYBADAQBAEAQNvcHf6QvTjO1urMrxfIsQxvHgEAMBAEAQBA29wd/gC9ON7a6zyvH8mxTG8lAQAw
EAQBAECwHf4AxTju293rrKMoyjGsgyoBADAQBAEAQLAd/gC9wMAJAAABdiAn+0bAwADLCAVQFJBV
H6cAAAAABzSiwYGBQYAAzFtVAQAwEAQBAEgARERfyF/7pAVjYfrr58rKzw9VOQAPdDku3Owcmy/K
sfyjLQEAMBAEAQBAoB39YL05Lt7sjJ82y3JMxy0BAEAQBAEAQKAd/NDFOW7g7PyzO8tyvOctAQBA
EAQBAECgHfzQxTlu5e1s0zzLsw0DLQEAQBAEAQBAkB38MMU5juTt3O87y7NdEy8BAEAQBAEAQJAd
/DDFOb7o7j0HPcvzrRs0AQAwEAQBAECAHfugxTm+6+6tGz/Ms+0XOwEAMBAEAQBAcB37AN457uvv
HSdDzTQtH0EBADAQBAEAQHAd+nDFwMAJAAABdiAoDsfAwADMCAVQFJBVH6cAAAAABzFiwYGBQYAA
zFtVAQAwEAQBAEgARERfyD/7tAVDYbg75grKzw9VOQAPdAEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQ
BFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVV
VVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAQBAE
AQBFVVVFVVVVVVVQEAQBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAQBAEAQBFVVVFVV
VVVVVQEAwMAJAAABdiAoIkjAwADNCAVQFJBVH50AAAAABzeiwYGBQYAAzFtVAQAwEAQBAEf8RERf
yD/7tAWTYiu76IrKzw9VOQAPdDAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBAEAQBAEA
RVVVRVVVVVVVUBAEAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBAEAQBAEARVVVRVVVVV
VVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBA
EARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQBAEARVVVRVVVVVVVUBADAQwMAJAAABdiAo
NbXAwADOCAVQFJBVH6cAAAAABzFiwYGBQYAAzFtVAQBAEAQBAEgARERfyB/7tAWTYiwb6MrKzw9V
OQAPdAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAE
VVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVV
VVAQBAEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQB
AEVVVUVVVVVVVVAQBAEAQBAEVVVUVVVVVVVVAQAwEAQBwMAJAAABdiAoSSvAwADPCAVQFJBVH6cA
AAAABy9iwYFBQYAAzFtVAQAwEAQBAEf8RERfyC/7tAVDYZfr5drKzw9VOQAPdABFVVVFVVVVVVVQ
EAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAQBAEAQBFVVVFVVVVVVVQEAMBAEAQBF
VVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVV
VQEAQBAEAQBFVVVFVVVVVVVQEAQBAEAQBFVVVFVVVVVVVQEAMBAEAQBFVVVFVVVVVVVQEAQBAEAQ
BFVVVFVVVVVVVQEAQBAEAQBFwMAJAAABdiAoXITAwADQCAVQFJBVH6cAAAAABy9iwYFBQYAAzFtV
AQAwEAQBAEf8RERfyA/7tAVDYcjb3eaq2s8PVTkAD3RVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVV
AQAwEAQBAEVVVUVVVVVVVVAQBAEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAE
VVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVV
VVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAQAwEAQBAEVVVUVVVVVVVVAAAAAAAA
AAAAAMDACQAAAXYgKHAGwMAA0QgFUBSQVR+nAAAAAAcvYsFBQQGAAMxbVQEAMBAEAQBH/EREX8f/
+7QFk2Ibq/hK2s8PVTkAD3Rhci1TQSDh3s8gyOHb3cogx+Hd1sfBISDH5Mcg5Mft3S0xIMPm4SDe
49EgxdXY5Mfa7SDMx+Pa7SDj5CDP5uHJIMfhxePH0cfKIObh3s8g2uPhINrh7CDI5MfG7SDd0e3e
IOPkINjhyMkgx+Hl5M/TySDH4cXjx9HHyu3m5CDj5CDH4czH49rJIMfhw+PR7d/tySDd7SDH4dTH
0d7JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwAkAAAF2ICiD
ccDAANIIBVAUkFUfpwAAAAAHL2LBQUEBgADMW1UBADAQBAEASABERF/H//ukBXNh+nv3utrPD1U5
AA90YXItU0Egx+Hd0e3eIMfh0O0g2uPhINrh7CDK1ePt4+0g5sjkx8btIOXmOiDO4e3dySDH4ePl
7dHtoSDayM/H4eHlIMfh1M3toSDdx8/tySDH4ePa7eTtoSDj7cvHwSDH4dTt0sfm7aEgw83jzyDH
4dTH2tGhIM3VySDa4e0g5tTt48fBIMfh49HS5t7tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwAkAAAF2ICiW38DAANMIBVAUkFUfnQAA
AAAHNKLBQUEBgADMW1UBADAQBAEAR/xERF/Ib/u0BYNiGwv4CtrPD1U5AA90YXItU0Eg3+PHIN7H
4yDd0e3eIMXPx9HJIMfh49TR5tog4+Qg49Hf0iDjzePPIMjkINHH1M8g4eHd1sfBIObl4yDFyNHH
5e3jIMfh3sfT4+2hIM3VySDH4ePY0ebU7SDm3cfY48kg4ebKx+UgyMfhxdTRx90g2uHsIOPl48rt
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAADAwAkAAAF2ICirRsDAANQIBSwUkFUfnQAAAAAHMWLBQUEBgADMW1UB
ADAQBAEASABERF/Ib/u0BVNhyJv2itrPD1U5AA90YXItU0Egx+THIMvj0ckgx9PKy+PH0SDVx83I
IMfh0+PmIMfh1O3OIOPN488gyOQg0cfUzyDC4SDj38rm4yDd7SDjzOPm2skg1dvd7dHJIOPkIMPI
5MfBIObI5MfKIMfhxePH0cfKIN7I4SDD38vRIOPkINrU0ckg0+Tmx8ouIObH4cLkIMPVyM3KIMzH
49rHyiDP5uHJIMfhxePH0cfKIN7Hz9HJINrh7CDI5MfBIMPe48fRIMXV2OTH2u3JAAAAAAAAAAAA
AAAAwMAJAAABdiAovqPAwADVCAVQFJBVH6cAAAAABy9iwUFBAYAAzFtVAQAwEAQBAEf8RERfyD/7
tAVTYag79hrazw9VOQAPdGFyLVNBIObh3s8g5N7UINrh7CDU2sfRIOPl48rtIN7V7c/JIOHh1Mfa
0ckgx+HF48fRx8rtySDa5tTJIMjkyiDO4e3dySDH4dPm7c/tIObH4crtIMPY4d4g2uHt5ccg1cfN
yCDH4dPj5iDH4dTtziDjzePPIMjkINHH1M8gwuEg49/K5uMg4d7IICLdysfJIMfh2tHIIgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMAJAAABdiAo0gHA
wADWCAUsFJBVH50AAAAABzFiwUFBAYAAzFtVAQBAEAQBAEf8RERfyH/7tAVDYbiL9krazw9VOQAP
dGFyLVNBIMfh3tXtz8kg5e0gIsjR3uwg0ebTIMfh1NHH7d0g48cgyOTS4SDdx+Hm2MfloSDN7csg
x+HY5u3hIMfh5Mft3SDh7SDdx+Hk2dHJIM3hx+WhIOTH7d0g5t7P0eUg5Mft3SDm3+Egx+Ha0cgg
ytHWx+UiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMAJAAABdiAo5WnAwADXCAUsFJBVH6cAAAAA
By9iwUFBAYAAzFtVAQAwEAQBAEgARERfyJ/7xAVDYafL9brazw9VOQAPdP8AAP///wAAgTUQvgD/
hQEADAPoAAQAyAEHAAYAAAABAAADjwD/zgAAADIAZADIHbAdsB2wHbAdsAD6AAafKaIAAAAAAAAA
AAAALgAvACsALwAz/0H/AQAAGQABAAADoWUKRkNlM0NlCkZDZTNDZQpGQ2UzQ2UKRkNlM0NlCkZD
ZTNDZUYxMXQ5MDF0REZ0NkV0MjExY0JBcThBcTY5YwoKRkNlM0NlCkZDZTNDZQpGQ2UzQ2UKRkNl
M0NlCkZDZTNDZUYxMXQ5wMAJAAABdiAo+LDAwADb3AgFLBSQVR+nAAAAAAcsYsFBQQGAAMxbVQEA
MBAEAQBIAEREX8jP+8QFM2GGXASq2s8PVToAD3Q5/u3vTRdKzTRdI0UBADAQBAEAQHAd+nC9Of7v
780jTs20jTtIAQBAEAQBAEBgHfnQxTo+8PAtL1LOdM1TSAEAMBAEAQBAYB35QMU6TvHwnTtVzvT9
Y0sBAEAQBAEAQFAd+UDSOj738Q1PV891LW9NAQBAEAQBAEBQHfiwxTpO9PFtX1jQNV17UAEAQBAE
AQBAQB34EL06bvnxzWtb0PWNh1QBADAQBAEAQDAd+BDFOq768j13X9H1vYtYAQAwEAQBAEAwHfeA
vcDACQAAAXYgKQwiwMAAwQgFLBSQVR+dAAAAAAcvYsFBQQGAAMxbVQEAMBAEAQBH/EREX8h/+8QF
Q2GXbAWa2t8PVToAD3Q6nvzynYdh0rXtl1sBADAQBAEAQCAd9uDFOv7+8v2PZdO2HadeAQAwEAQB
AEAgHfbgxTq+//N9l1/Sdk2vWgELcawEAQagFmX9YOo6/wDzzaM5z3Ztu04BDbFIBAEAQBTx/NEP
Ov8D872nHcs2bWdSAQjxlAQmAFAGZf8A9jr/BfPtpxjK9jynVwEAsBAEOYBQBCn80QI6/wT0HXcn
zHXcC1sbgEAoBDNAUAVd/gECOt8F9CzrNsz1e+tdNwBQEDUUgFAFdf6Q9sDACQAAAXYgKR+nwMAA
wggFLBSQVR+nAAAAAAcvYsFBQQGAAMxbVQEAMBAEAQBH/EREX8iP+8QFM2F2bATK2t8PVToAD3Q6
/wX0PFdBzfR8U1o5gFAUMQEEEAVd/pD2Ou8G9Dv/Sc30HJs/IkBQICgBDKAF/f+RAjq/BfQ8G03N
s2zTDwGA4DBOAQ6wBXX/AQ863wb0LFs9zPMc8ucBSXBkIAFLoAZOAMECOq8G9CyTGsvynQLZAUzQ
YHcCg7AGqgFhGzq/BfQcvvfK8Yzm7gGMYIRmGABgBxoCkPY6nwL0DM7iyTDsWwMDSBBwfioAUAey
A8EbOo8B8+zG48gvi+MTBYCAaNUmAFAGkgMg9sDACQAAAXYgKTLuwMAAwwgFLBSQVR+dAAAAAAcx
YsFBQQGAAMxbVQEAQBAEAQBH/EREX8mv+8QFQ2GXrAXK2t8PVToAD3Q6PwDzvJL2xy47nx0b29xQ
lL0l29zb3AeGBPEnOm7+84wvBcYta4MfHUBQeNvdFsFwBwYEUQI6Dv3zW/sPxaxryxsQ29xgePIB
gZAFigKRAjoe+/ML4xTE68wPDRjb3LBg2QGFkAZ+A8ECOf758ru/E8RrfDb5FoCwONoBhdAGQgPb
3PY5zvnya88NxGsMTuoBAPAo5wGFMAUaApD2Oa728hv3AcPq7E7eAURQPL4CiDAGZgRRDzmu9PHM
EvDDqzwqygFG4CyFB0owFwYE8RvAwAkAAAF2IClGYsDAAMQIBSwUkFUfnQAAAAAHL2LBQUEBgADM
W1UBADAQBAEAR/xERF/Jr/vEBUNhhtwFGtrfD1U6AA90OY7z8Ywa3cPre/69BElwNJkKxXAXSgYh
DzmO8/E8CsjDa3vuyAbLsFB4DoBgFn4FgSc5bu/w++62wuwLltkEyXAkGSiAsCYSBPD2OV7v8Lvm
tsKsuw7hAoIAGDE229zgJQID29z2OS7t8GvSysIs2qLiGQBwGDIzQPAlugRRDzke6/Arbtjb3O1a
kuI1ANDoCxTb3NvcNboE8Rs5Duzv290G3r4tywbkNcEgtAsBxRA1dgRRGzje6e+K1uG9LhtK0iMA
8QAJAstQNioE8Q/AwAkAAAF2IClavMDAAMUIBSwUkFUfnQAAAAAHNKLBQUEBgADMW1UBADAQBAEA
R/xERF/oX/u0BVNhySwWqtrfD1U6AA90OP7q70ry5bguO2q6AUCi7A4CyRBFdgTw9jje6O8LOuCx
7it+swII8uQSA0UQRmYGIPY4vujuy2LMra4rgrwCiPM0EAOAUFWiBYECOM7l7pt6y6luC3LOAkBz
YBoZAIBVXgTxDzi+5e5batWm7dvdFtgM29ySzCsmQWBmwgaw9ji+5O4LSt6lLar22RHb3JN4PA0B
oGZ+BrD2OL7i7bse4qNtWz7WHQGjAD4BxqB2TgdQ9jiu4e1q+uCi7UtuxhAB01QcAYYwdhIGsQ/A
wAkAAAF2ICluL8DAAMYIBSwUkFUfnQAAAAAHL2LBQUEBgADMW1UBADAQBAEASABERF/Ir/vEBVNh
t7wVytrfD1U6AA90OI7g7Rse3KDta4rBAgZzgBwCAgB1ogYhAjh+3+zLSsmgLVuWxQJIY2AlA4DQ
hf4HUQ84ft7se2rb3J7tS3LOAcLzRDAd29zQhc4GsRs4XtzsK27Bn60K1tUFQVJEQjNBEJW6BrEb
OH7b3evb3TrJoGyqatog29zS5EUg29ywlYoGsQ84LtrrerbPoWxKjt86QWFoSQZA0KWKB1D2OD7Y
6wpG0qSr6tbYMADyGEADR6ClXgaw9jf+1uqqNtikq7sKuAhAoaw/BE5AtUYGsQLAwAkAAAF2ICmB
iMDAAMcIBSwUkFUfnQAAAAAHMWLBQUEBgADMW1UBADAQBAEAR/xERF8=

```

**Comment by kng** [comment]
I'm closing this, somehow the file got corrupted, seems to work stable now.
