### ISSUE TITLE
/usr/local/bin/grsat-wrapper.sh: line 83: kill: (xxx) - No such process

### ISSUE THREAD

**Issue by 9V1KG** [kng/satnogs_gr-satellites#9]
I love the program, runs w/o problems, but in the log for each observation I get:
`usr/local/bin/grsat-wrapper.sh: line 83: kill: (xxx) - No such process`
after stopping of the observation.
No idea, what to do ...

**Comment by kng** [comment]
Sounds like the process dies prematurely.
The (xxx) is a reasonable, changing pid nr ?
While a supported obs is running, do you see the process with `ps ax|grep gr_satellites` ?

` 9218 ?        Sl     1:09 /usr/bin/python3 /usr/local/bin/gr_satellites 39433 --samp_rate 48000 --iq --throttle --udp --udp_port 57356 --udp_raw --start_time 2022-05-23T06:12:44 --kiss_out /tmp/.satnogs/grsat_5977771.kss --ignore_unknown_args --use_agc`

**Comment by 9V1KG** [comment]
Yes, (xxx) is the changing pid nr.
I have to check, whether I can see the process. Will come back to you.

**Comment by kng** [comment]
You can also check if there is some log files left, /tmp/.satnogs/grsat_*.log
Empty logs are automatically removed.

**Comment by 9V1KG** [comment]
Currently for an observation of a non supported satellite:
```
Traceback (most recent call last):
  File "/usr/local/bin/gr_satellites", line 316, in <module>
    main()
  File "/usr/local/bin/gr_satellites", line 301, in main
    tb = gr_satellites_top_block(parser)
  File "/usr/local/bin/gr_satellites", line 179, in __init__
    self.setup_input()
  File "/usr/local/bin/gr_satellites", line 221, in setup_input
    return self.setup_udp_input()
  File "/usr/local/bin/gr_satellites", line 264, in setup_udp_input
    self.options.udp_port, 1472, False)
  File "/usr/lib/python3/dist-packages/gnuradio/blocks/blocks_swig6.py", line 1252, in make
    return _blocks_swig6.udp_source_make(itemsize, host, port, payload_size, eof)
RuntimeError: open: Address family not supported by protocol
```

**Comment by 9V1KG** [comment]
The above shows:
```
gr-satellites: Observation: 5977990, Norad: 51439, Name: GASPACS, Script: satnogs_fsk.py
gr-satellites: Starting observation 5977990
gr-satellites: running at 57600 sps
...
gr-satellites: Observation: 5977990, Norad: 51439, Name: GASPACS, Script: satnogs_fsk.py
gr-satellites: Stopping observation 5977990
/usr/local/bin/grsat-wrapper.sh: line 83: kill: (2542) - No such process
```

**Comment by kng** [comment]
Very important to follow the detailed [installation instructions](https://gr-satellites.readthedocs.io/en/latest/installation.html#dependencies)
The runtime errors from gr_satellites suggests some problem with the compilation. I've seen similar on my systems and the compilation was seemingly happy, go figure.
It complains on the udp_source support, but I have no clue why it fails.

**Comment by 9V1KG** [comment]
Yes, I did follow step by step, and I didn't notice any problem. So, clean/delete and recompile?

**Comment by kng** [comment]
Yeah, worth a shot. Update the git repo. Inspect the result of cmake to see if it complains on something.
You should probably check with @daniestevez over at [his repo](https://github.com/daniestevez/gr-satellites)

**Comment by 9V1KG** [comment]
Do I need to provide an UDP port in the satnogs-setup or is there a default?
I ran the 16 gr_satellites test (make test), all passed.
gnu radio version and gr_satellites version also match together.

**Comment by kng** [comment]
The host is mandatory, port has a default value. And as it's udp it will just sit there and listen even if nothing sends to it.
What have you set the UDP settings to ? `grep UDP /etc/default/satnogs-client`

**Comment by 9V1KG** [comment]
UDP_DUMP_HOST="127.0.0.1"

**Comment by 9V1KG** [comment]
Something wrong with the sample rate? Taking the sample rate of my SDR (3000000)?
```
May 23 17:43:15 satnogs satnogs-client[5367]:   File "/usr/bin/satnogs_fsk.py", line 527, in main
May 23 17:43:15 satnogs satnogs-client[5367]:     tb = top_block_cls(antenna=options.antenna, baudrate=options.baudrate, bb_freq=options.bb_freq, bw=options.bw, dc_removal=options.dc_removal, decoded_data_file_path=options.decoded_data_file_path, dev_args=options.dev_args, doppler_correction_per_sec=options.doppler_correction_per_sec, enable_iq_dump=options.enable_iq_dump, file_path=options.file_path, framing=options.framing, gain=options.gain, gain_mode=options.gain_mode, iq_file_path=options.iq_file_path, lo_offset=options.lo_offset, other_settings=options.other_settings, ppm=options.ppm, rigctl_port=options.rigctl_port, rx_freq=options.rx_freq, samp_rate_rx=options.samp_rate_rx, soapy_rx_device=options.soapy_rx_device, stream_args=options.stream_args, tune_args=options.tune_args, udp_IP=options.udp_IP, udp_dump_host=options.udp_dump_host, udp_dump_port=options.udp_dump_port, udp_port=options.udp_port, waterfall_file_path=options.waterfall_file_path)
May 23 17:43:15 satnogs satnogs-client[5367]:   File "/usr/bin/satnogs_fsk.py", line 98, in __init__
May 23 17:43:15 satnogs satnogs-client[5367]:     tune_args, settings, samp_rate_rx, "fc32")
May 23 17:43:15 satnogs satnogs-client[5367]:   File "/usr/lib/python3/dist-packages/soapy/soapy_swig.py", line 166, in make
May 23 17:43:15 satnogs satnogs-client[5367]:     return _soapy_swig.source_make(nchan, device, dev_args, stream_args, tune_args, other_settings, sampling_rate, type)
May 23 17:43:15 satnogs satnogs-client[5367]: RuntimeError: soapy::source: Unsupported sample rate (3000000.000000).  Rate must be in the range [8000.000000, 8000.000000] [16000.000000, 16000.000000] [22050.000000, 22050.000000] [32000.000000, 32000.000000] [44100.000000, 44100.000000] [48000.000000, 48000.000000] [96000.000000, 96000.000000]
May 23 17:43:19 satnogs satnogs-client[5367]: gr-satellites: Observation: 5973185, Norad: 41460, Name: AAUSAT_4, Script: satnogs_fsk.py
May 23 17:43:19 satnogs satnogs-client[5367]: gr-satellites: Stopping observation 5973185
```

**Comment by daniestevez** [comment]
>  File "/usr/local/bin/gr_satellites", line 264, in setup_udp_input
    self.options.udp_port, 1472, False)
  File "/usr/lib/python3/dist-packages/gnuradio/blocks/blocks_swig6.py", line 1252, in make
    return _blocks_swig6.udp_source_make(itemsize, host, port, payload_size, eof)
RuntimeError: open: Address family not supported by protocol

Can you modify `/usr/local/bin/gr_satellites`, add
```
print(size, self.options.udp_ip, self.options.udp_port)
```
immediately before line 264 and run `gr_satellites` again?

Also, what version of gr-satellites and GNU Radio are you using?

**Comment by 9V1KG** [comment]
Daniel,
I am running the programs on a raspberry pi 4, Versions: gr_satellites v3.14.0-git, gnuradio '3.8.2.0'
I added the print line, but cannot find any print output. 
I have another installation of gr_satellites running on my Linux PC. When I start GQRX with udp output and gr_satellites with udp input, everything works fine, no runtime errors. For sure the problem is my gr_satellite installation on the Raspi 4, and not your part. I will recompile, try again and keep you updated.
Thanks so far!

**Comment by 9V1KG** [comment]
After re-installation of gr-satellites version 3.13.0 no more runtime error. It seems to work now!
Just warnings in the log
`gr::log :WARN: udp_source0 - Too much data; dropping packet.`
You can close the issue. Thanks again!

**Comment by janvgils** [comment]
Check and possible change /etc/gnuradio/conf.d/udp.conf 
I had similar problems with high sample rates.

```
# place in: /etc/gnuradio/conf.d/udp.conf or ~/.gnuradio/config.conf
# 512 looks fine for complex stream at 128ksps, 8192 handles at least 600ksps
[udp_blocks]
# buf_size_payloads = 512
# buf_size_payloads = 2048
# buf_size_payloads = 3072
buf_size_payloads = 4096
# buf_size_payloads = 8192
```
